{% set name = "pathvalidate" %}
{% set version = "2.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #git_url: "https://github.com/thombashi/{{ name }}.git"
  #git_rev: "v{{ version }}"
  #git_depth: 1
  url: https://github.com/thombashi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d64d1d2d6f2df501b8e3a330f269170ccb67f078cf4fd11de865b5fc83377a05

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pathvalidate
  requires:
    - faker
    - pytest

about:
  home: "https://github.com/thombashi/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "pathvalidate is a Python library to sanitize/validate a string such as filenames/file-paths/etc."
  doc_url: "https://{{ name }}.rtfd.io/"
  dev_url: "https://github.com/thombashi/{{ name }}"

extra:
  recipe-maintainers:
    - thombashi
